resources:
- name: sample-project
  type: git
  source:
    uri: https://github.com/walrusfruitcake/concourse-multi-image-sample-project.git
    branch: master

- name: image-to-local-registry
  type: docker-image
  source:
    repository: localhost:5000/debian

- name: jessie-image
  type: docker-image
  source:
    repository: debian
    tag: jessie

jobs:
- name: push-docker-image
  plan:
  - aggregate:
    - get: sample-project
    - get: jessie-image
      params:
        save: true
  - put: image-to-local-registry
    params:
      load_base: jessie-image
      build: sample-project/docker/test

- name: hello-via-npm
  plan:
  - get: sample-project
    trigger: false
  - task: say-hello-in-yavascript
    file: sample-project/flight-tasks/hello-javascript.yml
  - task: say-yay-in-python-36
    file: sample-project/flight-tasks/hello-python-36.yml
