resources:
- name: sample-project
  type: git
  source:
    uri: https://github.com/walrusfruitcake/concourse-multi-image-sample-project.git
    branch: master

jobs:
- name: hello-from-javascript
  plan:
  - get: sample-project
    trigger: false
  - task: say-hello-in-yavascript
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node}
      inputs:
      - name: sample-project
      run:
        dir: sample-project
        path: npm
        args: ["start"]
