resources:
- name: sample-project
  type: git
  source:
    uri: https://github.com/walrusfruitcake/concourse-multi-image-sample-project.git
    branch: master

jobs:
- name: hello-from-javascript
  plan:
  - get: sample-project
    trigger: false
  - task: say-hello-in-yavascript
    file: sample-project/flight-tasks/hello-javascript.yml
  - task: say-yay-in-python-36
    file: sample-project/flight-tasks/hello-python-36.yml
